config/routes.rb
Rails.application.routes.draw do
  root "games#index"

  resources :games
  resources :users, only: :show
  resources :bet, only: :show

  namespace :api, defaults: { format: 'json' } do
    resources :users, only: [:index, :create]
    resources :bets, only: [:index, :create]
    resources :games, only: [:index]
  end
end

app/models/bet.rb
class Bet < ActiveRecord::Base
  belongs_to :game
  belongs_to :user
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :bets

  def dt_game
    read_attribute(:dt_game).strftime('%d/%m/%Y') unless read_attribute(:dt_game).nil?
  end

  def hr_game
    read_attribute(:hr_game).strftime('%H:%M') unless read_attribute(:hr_game).nil?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bets
end

app/controllers/api/bets_controller.rb
module API
  class BetsController < ActionController::Base
    def index
      render json: Bet.all
    end

    def create
      bet = Bet.new(bet_params)
      render json: bet, location: bet_path(bet) if bet.save
    end

    private
    def bet_params
      params.require(:bet).permit(:user_id, :game_id, :score_team_a, :score_team_b)
    end
  end
end

app/controllers/api/games_controller.rb
module API
  class GamesController < ActionController::Base
    def index
      render json: Game.all.select(:id, :nr, :dt_game, :hr_game, :team_a, :team_b, :score_ta, :score_tb)
    end
  end
end

app/controllers/api/users_controller.rb
module API
  class UsersController < ActionController::Base
    def index
      render json: User.all
    end

    def create
      user = User.new(user_params)
      render json: user, location: user_path(user) if user.save
    end

    private
    def user_params
      params.require(:user).permit(:sid, :name)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  def index
    @games = Game.order(:dt_game)
  end

  def show
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to games_path
      flash[:success] = "Jogo cadastrado com sucesso"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @game.update(game_params)
      redirect_to games_path
      flash[:success] = "Jogo atualizado com sucesso"
    else
      render :edit
    end
  end

  def destroy
    @game.destroy
    redirect_to games_path
    flash[:success] = "Jogo removido com sucesso"
  end

  private
  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:dt_game, :hr_game, :team_a, :team_b, :score_ta, :score_tb)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_form.html.erb
<%= simple_form_for @game, defaults: { label: false } do |f| %>
  <div class="row">
    <div class="col-lg-4">
      <div class="form-group">
        <%= f.input :nr, label: "Número do Jogo", input_html: { class: "form-control" } %>
      </div>
    </div>

    <div class="col-lg-4">
      <div class="form-group">
        <%= f.input :dt_game, label: "Data do Jogo", as: :string, input_html: { class: "form-control dt_game", value: f.object.dt_game } %>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="form-group">
        <%= f.input :hr_game, label: "Horário do Jogo", as: :string, input_html: { class: "form-control", value: f.object.hr_game } %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6">
      <div class="form-group">
        <%= f.input :team_a, label: "Time A", input_html: { class: "form-control" } %>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="form-group">
        <%= f.input :team_b, label: "Time B", input_html: { class: "form-control" } %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6">
      <div class="form-group">
        <%= f.input :score_ta, label: "Resultado Time A", input_html: { class: "form-control" } %>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="form-group">
        <%= f.input :score_tb, label: "Resultado Time B", input_html: { class: "form-control" } %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.submit "Salvar", class: "btn btn-success" %>
    <%= link_to "Voltar", games_path, class: "btn btn-link" %>
  </div>
<% end %>

app/views/games/edit.html.erb
<%= render 'form' %>

app/views/games/index.html.erb
<table class="table table-hover">
  <thead>
    <th>Jogo</th>
    <th>Data do Jogo</th>
    <th>Resultado</th>
    <th></th>
  </thead>
  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= "#{game.team_a} x #{game.team_b}" %></td>
        <td><%= "#{game.dt_game} #{game.hr_game}" %></td>
        <td></td>
        <td>
          <%= link_to "Editar", edit_game_path(game) %>
          <%= link_to "Remover", game, method: :delete, data: { confirm: "Deseja remover esse jogo?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bolaao</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <!-- Static navbar -->
      <div class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "Home", root_path, class: "navbar-brand" %>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to "Cadastrar Jogo", new_game_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </div>

      <!-- Main component for a primary marketing message or call to action -->
      <%= yield %>
    </div>
  </body>
</html>